DROP TABLE if exists family CASCADE;
DROP TABLE if exists field_trial CASCADE;
DROP TABLE if exists journal CASCADE;
DROP TABLE if exists pedigree CASCADE;
DROP TABLE if exists plant CASCADE;
DROP TABLE if exists site CASCADE;
DROP TABLE if exists split_wood_tests CASCADE;
DROP TABLE if exists taxa CASCADE;
DROP TABLE if exists test_detail CASCADE;
DROP TABLE if exists test_spec CASCADE;
DROP TABLE if exists u07m_2013 CASCADE;
DROP VIEW if exists avw_family;
DROP VIEW if exists avw_family_phase_seed_germ_summary;
DROP VIEW if exists avw_family_phase_summary;
DROP VIEW if exists avw_field_trial;
DROP VIEW if exists avw_gpf_split_wood_tests;
DROP VIEW if exists avw_journal;
DROP VIEW if exists avw_plant;
DROP VIEW if exists avw_site;
DROP VIEW if exists avw_taxa;
DROP VIEW if exists avw_test_detail;
DROP VIEW if exists avw_test_spec;
DROP VIEW if exists avx_female_parent_germination_rate_summary;
DROP VIEW if exists avx_female_parent_germination_rates;
DROP VIEW if exists avx_male_parent_germination_rate_summary;
DROP VIEW if exists avx_male_parent_germination_rates;
DROP VIEW if exists gpf1_figured_wood_split_tests;
DROP VIEW if exists gpf2_figured_wood_split_tests_summary;
DROP VIEW if exists v1_field_trial_master_summary;
DROP VIEW if exists v2_field_trial_test_spec_summary;
DROP VIEW if exists v3_field_trial_summary;
DROP VIEW if exists v4_field_trial_test_spec_2019postne;
DROP VIEW if exists v5_field_trial_stocktypes_2019_post_sites;
DROP VIEW if exists v6_field_trial_stocktypes_2019_post_sites_summary;
DROP VIEW if exists v7_field_trial_ranked_summary;
DROP VIEW if exists va1_master_test_detail;
DROP VIEW if exists va2_all_nursery_rankings;
DROP VIEW if exists va2_nursery_stocktype_test_detail;
DROP VIEW if exists va3_nursery_summary_test_detail;
DROP VIEW if exists va4_nursery_dormant_cutting_summary;
DROP VIEW if exists vw_2019_1_nursery;
DROP VIEW if exists vw_2019_2_nursery_key_stock_summary;
DROP VIEW if exists vw_2019_3_nursery_stock_summary;
DROP VIEW if exists vw_2019_4_nursery_action_stock_summary;
DROP VIEW if exists vw_2019_5_nursery_field_summary;
DROP VIEW if exists vw_2019_6_nursery_summary_by_rep_nbr;
DROP VIEW if exists vw_2019_7_stock;
DROP VIEW if exists vw_2019_8_stock_summary;
DROP VIEW if exists vw_2019_field_plus_clones;
DROP VIEW if exists vw_2019_nursery_field_clone_summary;
DROP VIEW if exists vw_u07m_2013;
